<?php
/**
 * Obsolete pathes
 *
 * Format: array(<path>[, <replacement>])
 *
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
return [
    ['/app/code/core/Mage', '/app/code/Magento'],
    ['/lib/Magento/App', '/lib/Magento/Framework/App'],
    ['/Dev/tests/integration/testsuite/Magento/App', '/Dev/tests/integration/testsuite/Magento/Framework/App'],
    ['/Dev/tests/unit/testsuite/Magento/App', '/Dev/tests/unit/testsuite/Magento/Framework/App'],
    ['/lib/Magento/Data', '/lib/Magento/Framework/Data'],
    ['/Dev/tests/integration/testsuite/Magento/Data', '/Dev/tests/integration/testsuite/Magento/Framework/Data'],
    ['/Dev/tests/unit/testsuite/Magento/Data', '/Dev/tests/unit/testsuite/Magento/Framework/Data'],
    ['/lib/Magento/Filesystem', '/lib/Magento/Framework/Filesystem'],
    [
        '/Dev/tests/integration/testsuite/Magento/Filesystem',
        '/Dev/tests/integration/testsuite/Magento/Framework/Filesystem'
    ],
    ['/Dev/tests/unit/testsuite/Magento/Filesystem', '/Dev/tests/unit/testsuite/Magento/Framework/Filesystem'],
    ['/lib/Magento/Config', '/lib/Magento/Framework/Config'],
    ['/lib/Magento/Model', '/lib/Magento/Framework/Model'],
    ['/Dev/tests/integration/testsuite/Magento/Model', '/Dev/tests/integration/testsuite/Magento/Framework/Model'],
    ['/Dev/tests/unit/testsuite/Magento/Model', '/Dev/tests/unit/testsuite/Magento/Framework/Model'],
    ['/lib/Magento/View', '/lib/Magento/Framework/View'],
    ['/Dev/tests/integration/testsuite/Magento/View', '/Dev/tests/integration/testsuite/Magento/Framework/View'],
    ['/Dev/tests/unit/testsuite/Magento/View', '/Dev/tests/unit/testsuite/Magento/Framework/View'],
    ['/lib/Magento/DB', '/lib/Magento/Framework/DB'],
    ['/Dev/tests/integration/testsuite/Magento/DB', '/Dev/tests/integration/testsuite/Magento/Framework/DB'],
    ['/Dev/tests/unit/testsuite/Magento/DB', '/Dev/tests/unit/testsuite/Magento/Framework/DB'],
    ['/lib/Magento/Event', '/lib/Magento/Framework/Event'],
    ['/Dev/tests/integration/testsuite/Magento/Event', '/Dev/tests/integration/testsuite/Magento/Framework/Event'],
    ['/Dev/tests/unit/testsuite/Magento/Event', '/Dev/tests/unit/testsuite/Magento/Framework/Event'],
    ['/lib/Magento/Acl', '/lib/Magento/Framework/Acl'],
    ['/Dev/tests/integration/testsuite/Magento/Acl', '/Dev/tests/integration/testsuite/Magento/Framework/Acl'],
    ['/Dev/tests/unit/testsuite/Magento/Acl', '/Dev/tests/unit/testsuite/Magento/Framework/Acl'],
    ['/lib/Magento/Archive', '/lib/Magento/Framework/Archive'],
    [
        '/Dev/tests/integration/testsuite/Magento/Archive',
        '/Dev/tests/integration/testsuite/Magento/Framework/Archive'
    ],
    ['/Dev/tests/unit/testsuite/Magento/Archive', '/Dev/tests/unit/testsuite/Magento/Framework/Archive'],
    ['/lib/Magento/Backup', '/lib/Magento/Framework/Backup'],
    ['/lib/Magento/Session', '/lib/Magento/Framework/Session'],
    [
        '/Dev/tests/integration/testsuite/Magento/Session',
        '/Dev/tests/integration/testsuite/Magento/Framework/Session'
    ],
    ['/Dev/tests/unit/testsuite/Magento/Session', '/Dev/tests/unit/testsuite/Magento/Framework/Session'],
    ['/lib/Magento/Authorization', '/lib/Magento/Framework/Authorization'],
    ['/lib/Magento/Cache', '/lib/Magento/Framework/Cache'],
    ['/Dev/tests/integration/testsuite/Magento/Cache', '/Dev/tests/integration/testsuite/Magento/Framework/Cache'],
    ['/Dev/tests/unit/testsuite/Magento/Cache', '/Dev/tests/unit/testsuite/Magento/Framework/Cache'],
    ['/lib/Magento/ObjectManager', '/lib/Magento/Framework/ObjectManager'],
    [
        '/Dev/tests/integration/testsuite/Magento/ObjectManager',
        '/Dev/tests/integration/testsuite/Magento/Framework/ObjectManager'
    ],
    ['/Dev/tests/unit/testsuite/Magento/ObjectManager', '/Dev/tests/unit/testsuite/Magento/Framework/ObjectManager'],
    ['/lib/Magento/Exception', '/lib/Magento/Framework/Exception'],
    [
        '/Dev/tests/integration/testsuite/Magento/Exception',
        '/Dev/tests/integration/testsuite/Magento/Framework/Exception'
    ],
    ['/Dev/tests/unit/testsuite/Magento/Exception', '/Dev/tests/unit/testsuite/Magento/Framework/Exception'],
    ['/lib/Magento/Autoload', '/lib/Magento/Framework/Autoload'],
    [
        '/Dev/tests/integration/testsuite/Magento/Autoload',
        '/Dev/tests/integration/testsuite/Magento/Framework/Autoload'
    ],
    ['/Dev/tests/unit/testsuite/Magento/Autoload', '/Dev/tests/unit/testsuite/Magento/Framework/Autoload'],
    ['/lib/Magento/Translate', '/lib/Magento/Framework/Translate'],
    [
        '/Dev/tests/integration/testsuite/Magento/Translate',
        '/Dev/tests/integration/testsuite/Magento/Framework/Translate'
    ],
    ['/Dev/tests/unit/testsuite/Magento/Translate', '/Dev/tests/unit/testsuite/Magento/Framework/Translate'],
    ['/lib/Magento/Code', '/lib/Magento/Framework/Code'],
    ['/Dev/tests/integration/testsuite/Magento/Code', '/Dev/tests/integration/testsuite/Magento/Framework/Code'],
    ['/Dev/tests/unit/testsuite/Magento/Code', '/Dev/tests/unit/testsuite/Magento/Framework/Code'],
    ['/lib/Magento/Stdlib', '/lib/Magento/Framework/Stdlib'],
    ['/Dev/tests/integration/testsuite/Magento/Stdlib', '/Dev/tests/integration/testsuite/Magento/Framework/Stdlib'],
    ['/Dev/tests/unit/testsuite/Magento/Stdlib', '/Dev/tests/unit/testsuite/Magento/Framework/Stdlib'],
    ['/lib/Magento/Phrase', '/lib/Magento/Framework/Phrase'],
    ['/Dev/tests/integration/testsuite/Magento/Phrase', '/Dev/tests/integration/testsuite/Magento/Framework/Phrase'],
    ['/Dev/tests/unit/testsuite/Magento/Phrase', '/Dev/tests/unit/testsuite/Magento/Framework/Phrase'],
    ['/lib/Magento/Locale', '/lib/Magento/Framework/Locale'],
    ['/Dev/tests/integration/testsuite/Magento/Locale', '/Dev/tests/integration/testsuite/Magento/Framework/Locale'],
    ['/Dev/tests/unit/testsuite/Magento/Locale', '/Dev/tests/unit/testsuite/Magento/Framework/Locale'],
    ['/lib/Magento/Message', '/lib/Magento/Framework/Message'],
    ['/Dev/tests/integration/testsuite/Magento/Message', '/Dev/tests/integration/testsuite/Magento/Framework/Message'],
    ['/Dev/tests/unit/testsuite/Magento/Message', '/Dev/tests/unit/testsuite/Magento/Framework/Message'],
    ['/lib/Magento/Logger', '/lib/Magento/Framework/Logger'],
    ['/Dev/tests/integration/testsuite/Magento/Logger', '/Dev/tests/integration/testsuite/Magento/Framework/Logger'],
    ['/Dev/tests/unit/testsuite/Magento/Logger', '/Dev/tests/unit/testsuite/Magento/Framework/Logger'],
    ['/lib/Magento/Error', '/lib/Magento/Framework/Error'],
    ['/Dev/tests/integration/testsuite/Magento/Error', '/Dev/tests/integration/testsuite/Magento/Framework/Error'],
    ['/Dev/tests/unit/testsuite/Magento/Error', '/Dev/tests/unit/testsuite/Magento/Framework/Error'],
    ['/lib/Magento/Filter', '/lib/Magento/Framework/Filter'],
    ['/Dev/tests/integration/testsuite/Magento/Filter', '/Dev/tests/integration/testsuite/Magento/Framework/Filter'],
    ['/Dev/tests/unit/testsuite/Magento/Filter', '/Dev/tests/unit/testsuite/Magento/Framework/Filter'],
    ['/lib/Magento/DomDocument', '/lib/Magento/Framework/DomDocument'],
    [
        '/Dev/tests/integration/testsuite/Magento/DomDocument',
        '/Dev/tests/integration/testsuite/Magento/Framework/DomDocument'
    ],
    ['/Dev/tests/unit/testsuite/Magento/DomDocument', '/Dev/tests/unit/testsuite/Magento/Framework/DomDocument'],
    ['/lib/Magento/Module', '/lib/Magento/Framework/Module'],
    ['/Dev/tests/integration/testsuite/Magento/Module', '/Dev/tests/integration/testsuite/Magento/Framework/Module'],
    ['/Dev/tests/unit/testsuite/Magento/Module', '/Dev/tests/unit/testsuite/Magento/Framework/Module'],
    ['/lib/Magento/Css', '/lib/Magento/Framework/Css'],
    ['/Dev/tests/integration/testsuite/Magento/Css', '/Dev/tests/integration/testsuite/Magento/Framework/Css'],
    ['/Dev/tests/unit/testsuite/Magento/Css', '/Dev/tests/unit/testsuite/Magento/Framework/Css'],
    ['/lib/Magento/Pear', '/lib/Magento/Framework/Pear'],
    ['/Dev/tests/integration/testsuite/Magento/Pear', '/Dev/tests/integration/testsuite/Magento/Framework/Pear'],
    ['/Dev/tests/unit/testsuite/Magento/Pear', '/Dev/tests/unit/testsuite/Magento/Framework/Pear'],
    ['/lib/Magento/Pricing', '/lib/Magento/Framework/Pricing'],
    ['/Dev/tests/integration/testsuite/Magento/Pricing', '/Dev/tests/integration/testsuite/Magento/Framework/Pricing'],
    ['/Dev/tests/unit/testsuite/Magento/Pricing', '/Dev/tests/unit/testsuite/Magento/Framework/Pricing'],
    ['/lib/Magento/Connect'],
    ['/lib/Magento/Framework/Connect'],
    ['/lib/internal/Magento/Framework/Connect'],
    ['/lib/Magento/Profiler', '/lib/Magento/Framework/Profiler'],
    ['/Dev/tests/unit/testsuite/Magento/Profiler', '/Dev/tests/unit/testsuite/Magento/Framework/Profiler'],
    [
        '/Dev/tests/integration/testsuite/Magento/Profiler',
        '/Dev/tests/integration/testsuite/Magento/Framework/Profiler'
    ],
    ['/lib/Magento/Simplexml', '/lib/Magento/Framework/Simplexml'],
    ['/Dev/tests/unit/testsuite/Magento/Simplexml', '/Dev/tests/unit/testsuite/Magento/Framework/Simplexml'],
    [
        '/Dev/tests/integration/testsuite/Magento/Simplexml',
        '/Dev/tests/integration/testsuite/Magento/Framework/Simplexml'
    ],
    ['/lib/Magento/Controller', '/lib/Magento/Framework/Controller'],
    [
        '/Dev/tests/integration/testsuite/Magento/Controller',
        '/Dev/tests/integration/testsuite/Magento/Framework/Controller'
    ],
    ['/Dev/tests/unit/testsuite/Magento/Controller', '/Dev/tests/unit/testsuite/Magento/Framework/Controller'],
    ['/lib/Magento/Convert', '/lib/Magento/Framework/Convert'],
    ['/Dev/tests/integration/testsuite/Magento/Convert', '/Dev/tests/integration/testsuite/Magento/Framework/Convert'],
    ['/Dev/tests/unit/testsuite/Magento/Convert', '/Dev/tests/unit/testsuite/Magento/Framework/Convert'],
    ['/lib/Magento/Shell', '/lib/Magento/Framework/Shell'],
    ['/Dev/tests/unit/testsuite/Magento/Shell', '/Dev/tests/unit/testsuite/Magento/Framework/Shell'],
    ['/Dev/tests/integration/testsuite/Magento/Shell', '/Dev/tests/integration/testsuite/Magento/Framework/Shell'],
    ['/lib/Magento/Encryption', '/lib/Magento/Framework/Encryption'],
    [
        '/Dev/tests/integration/testsuite/Magento/Encryption',
        '/Dev/tests/integration/testsuite/Magento/Framework/Encryption'
    ],
    ['/Dev/tests/unit/testsuite/Magento/Encryption', '/Dev/tests/unit/testsuite/Magento/Framework/Encryption'],
    ['/lib/Magento/Option', '/lib/Magento/Framework/Option'],
    ['/Dev/tests/unit/testsuite/Magento/Option', '/Dev/tests/unit/testsuite/Magento/Framework/Option'],
    ['/Dev/tests/integration/testsuite/Magento/Option', '/Dev/tests/integration/testsuite/Magento/Framework/Option'],
    ['/lib/Magento/Service', '/lib/Magento/Framework/Api'],
    ['/Dev/tests/unit/testsuite/Magento/Service', '/Dev/tests/unit/testsuite/Magento/Framework/Api'],
    ['/Dev/tests/integration/testsuite/Magento/Service', '/Dev/tests/integration/testsuite/Magento/Framework/Api'],
    ['/lib/Magento/System', '/lib/Magento/Framework/System'],
    ['/Dev/tests/unit/testsuite/Magento/System', '/Dev/tests/unit/testsuite/Magento/Framework/System'],
    ['/Dev/tests/integration/testsuite/Magento/System', '/Dev/tests/integration/testsuite/Magento/Framework/System'],
    ['/lib/Magento/Url', '/lib/Magento/Framework/Url'],
    ['/Dev/tests/unit/testsuite/Magento/Url', '/Dev/tests/unit/testsuite/Magento/Framework/Url'],
    ['/Dev/tests/integration/testsuite/Magento/Url', '/Dev/tests/integration/testsuite/Magento/Framework/Url'],
    ['/lib/Magento/Mview', '/lib/Magento/Framework/Mview'],
    ['/Dev/tests/unit/testsuite/Magento/Mview', '/Dev/tests/unit/testsuite/Magento/Framework/Mview'],
    ['/Dev/tests/integration/testsuite/Magento/Mview', '/Dev/tests/integration/testsuite/Magento/Framework/Mview'],
    ['/lib/Magento/Validator', '/lib/Magento/Framework/Validator'],
    ['/Dev/tests/unit/testsuite/Magento/Validator', '/Dev/tests/unit/testsuite/Magento/Framework/Validator'],
    [
        '/Dev/tests/integration/testsuite/Magento/Validator',
        '/Dev/tests/integration/testsuite/Magento/Framework/Validator'
    ],
    ['/lib/Magento/Xml', '/lib/Magento/Framework/Xml'],
    ['/Dev/tests/unit/testsuite/Magento/Xml', '/Dev/tests/unit/testsuite/Magento/Framework/Xml'],
    ['/Dev/tests/integration/testsuite/Magento/Xml', '/Dev/tests/integration/testsuite/Magento/Framework/Xml'],
    ['/lib/Magento/Interception', '/lib/Magento/Framework/Interception'],
    ['/Dev/tests/unit/testsuite/Magento/Interception', '/Dev/tests/unit/testsuite/Magento/Framework/Interception'],
    [
        '/Dev/tests/integration/testsuite/Magento/Interception',
        '/Dev/tests/integration/testsuite/Magento/Framework/Interception'
    ],
    ['/lib/Magento/Json', '/lib/Magento/Framework/Json'],
    ['/Dev/tests/unit/testsuite/Magento/Json', '/Dev/tests/unit/testsuite/Magento/Framework/Json'],
    ['/Dev/tests/integration/testsuite/Magento/Json', '/Dev/tests/integration/testsuite/Magento/Framework/Json'],
    ['/lib/Magento/Less', '/lib/Magento/Framework/Less'],
    ['/Dev/tests/unit/testsuite/Magento/Less', '/Dev/tests/unit/testsuite/Magento/Framework/Less'],
    ['/Dev/tests/integration/testsuite/Magento/Less', '/Dev/tests/integration/testsuite/Magento/Framework/Less'],
    ['/lib/Magento/File', '/lib/Magento/Framework/File'],
    ['/Dev/tests/unit/testsuite/Magento/File', '/Dev/tests/unit/testsuite/Magento/Framework/File'],
    ['/Dev/tests/integration/testsuite/Magento/File', '/Dev/tests/integration/testsuite/Magento/Framework/File'],
    ['/lib/Magento/Flag', '/lib/Magento/Framework/Flag'],
    ['/Dev/tests/unit/testsuite/Magento/Flag', '/Dev/tests/unit/testsuite/Magento/Framework/Flag'],
    ['/Dev/tests/integration/testsuite/Magento/Flag', '/Dev/tests/integration/testsuite/Magento/Framework/Flag'],
    ['/lib/Magento/Io', '/lib/Magento/Framework/Io'],
    ['/Dev/tests/unit/testsuite/Magento/Io', '/Dev/tests/unit/testsuite/Magento/Framework/Io'],
    ['/Dev/tests/integration/testsuite/Magento/Io', '/Dev/tests/integration/testsuite/Magento/Framework/Io'],
    ['/lib/Magento/Mail', '/lib/Magento/Framework/Mail'],
    ['/Dev/tests/unit/testsuite/Magento/Mail', '/Dev/tests/unit/testsuite/Magento/Framework/Mail'],
    ['/Dev/tests/integration/testsuite/Magento/Mail', '/Dev/tests/integration/testsuite/Magento/Framework/Mail'],
    ['/lib/Magento/HTTP', '/lib/Magento/Framework/HTTP'],
    ['/Dev/tests/unit/testsuite/Magento/Http', '/Dev/tests/unit/testsuite/Magento/Framework/HTTP'],
    ['/Dev/tests/integration/testsuite/Magento/HTTP', '/Dev/tests/integration/testsuite/Magento/Framework/HTTP'],
    ['/lib/Magento/Math', '/lib/Magento/Framework/Math'],
    ['/Dev/tests/unit/testsuite/Magento/Math', '/Dev/tests/unit/testsuite/Magento/Framework/Math'],
    ['/Dev/tests/integration/testsuite/Magento/Math', '/Dev/tests/integration/testsuite/Magento/Framework/Math'],
    ['/lib/Magento/Gdata', '/lib/Magento/Framework/Gdata'],
    ['/Dev/tests/unit/testsuite/Magento/Gdata', '/Dev/tests/unit/testsuite/Magento/Framework/Gdata'],
    ['/Dev/tests/integration/testsuite/Magento/Gdata', '/Dev/tests/integration/testsuite/Magento/Framework/Gdata'],
    ['/lib/Magento/Image', '/lib/Magento/Framework/Image'],
    ['/Dev/tests/unit/testsuite/Magento/Image', '/Dev/tests/unit/testsuite/Magento/Framework/Image'],
    ['/Dev/tests/integration/testsuite/Magento/Image', '/Dev/tests/integration/testsuite/Magento/Framework/Image'],
    ['/lib/Magento/Oauth', '/lib/Magento/Framework/Oauth'],
    ['/Dev/tests/unit/testsuite/Magento/Oauth', '/Dev/tests/unit/testsuite/Magento/Framework/Oauth'],
    ['/Dev/tests/integration/testsuite/Magento/Oauth', '/Dev/tests/integration/testsuite/Magento/Framework/Oauth'],
    ['/lib/Magento/Object', '/lib/Magento/Framework/Object'],
    ['/Dev/tests/unit/testsuite/Magento/Object', '/Dev/tests/unit/testsuite/Magento/Framework/Object'],
    ['/Dev/tests/integration/testsuite/Magento/Object', '/Dev/tests/integration/testsuite/Magento/Framework/Object'],
    ['/Dev/tests/unit/testsuite/Magento/Core/Model/View/Url', '/Dev/tests/unit/testsuite/Magento/Framework/View/Url'],
    ['/app/code/Magento/Core/Model/View/Url', '/lib/internal/Magento/Framework/View/Url'],
    ['/downloader'],
    ['/app/code/Magento/Core/Model/Design/Backend', '/app/code/Magento/Theme/Model/Design/Backend'],
    [
        '/Dev/tests/integration/testsuite/Magento/Core/Model/Design/Backend',
        '/Dev/tests/integration/testsuite/Magento/Theme/Model/Design/Backend'
    ],
    ['/app/code/Magento/Core/Model/Resource/Theme', '/app/code/Magento/Theme/Model/Resource/Theme'],
    [
        '/Dev/tests/integration/testsuite/Magento/Core/Model/Resource/Theme',
        '/Dev/tests/integration/testsuite/Magento/Theme/Model/Resource/Theme'
    ],
    ['/Dev/tests/unit/testsuite/Magento/Webapi/Service/Entity'],
    ['/app/code/Magento/Install'],
    ['/Dev/tests/integration/testsuite/Magento/Install'],
    ['/Dev/tests/static/testsuite/Magento/Test/Integrity/Magento/Install'],
    ['/Dev/tests/integration/testsuite/Magento/Test/Integrity/Modular/InstallWizardConfigFilesTest.php'],
    ['/Dev/tests/static/testsuite/Magento/Test/Legacy/Magento/Install'],
    ['/Dev/tests/unit/testsuite/Magento/Install'],
    ['/Dev/shell/install.php'],
    ['/Dev/shell/uninstall.php'],
    ['/app/design/install'],
    ['/app/etc/local.xml', '/app/etc/config.php'],
    ['/app/code/Magento/RecurringPayment'],
    ['/app/code/Magento/PayPalRecurringPayment'],
    ['/app/code/Magento/Weee/Model/Total/Quote/Nominal/Weee.php'],
    ['/app/code/Magento/Tax/Model/Sales/Total/Quote/Nominal/Subtotal.php'],
    ['/app/code/Magento/Tax/Model/Sales/Total/Quote/Nominal/Tax.php'],
    ['/app/code/Magento/SalesRule/Model/Quote/Nominal/Discount.php'],
    ['/app/code/Magento/Sales/Model/Quote/Address/Total/Nominal.php'],
    ['/app/code/Magento/Sales/Model/Quote/Address/Total/Nominal'],
    ['/app/code/Magento/Checkout/Block/Total/Nominal.php'],
    ['/app/code/Magento/Checkout/etc/sales.xml'],
    ['/app/code/Magento/Core/Model/TemplateEngine/Decorator/DebugHints.php'],
    ['/Dev/tests/unit/testsuite/Magento/Core/Model/TemplateEngine/Decorator/DebugHints.php'],
    ['/Dev/tests/unit/testsuite'],
    ['/app/code/Magento/Log'],
    ['/app/code/Magento/DesignEditor'],
    ['/Dev/tools/Magento/Tools/Migration'],
    ['/Dev/shell/dependency.php'],
    ['/Dev/tests/performance'],
];
